# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d2a482c98fe99d28f44014d615e59135e154c0ccdd1c05c7c724169ca5e37cea6dda22b4dbd1d68058c4cc5cfc108569ce031d8cb920db3de719f07766e3526

test:
  secret_key_base: fc9f4f9a593a21070697fceef9b79d06e31efd732a641185c75f03965693d9813e1d0319aabafdd11b1e22be1bf040ba12a5b3317b1881422814817a46f2c93a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
